### ISSUE TITLE
Feature: Option to override authuser parameters

### ISSUE THREAD

**Issue by IronCrystal** [lesiki/google-meet-default-account#1]
Sometimes other people will send google meet urls that already have authuser attached, but it's not going to align with my authuser param.

Can there be an option to override any existing authuser parameters?

**Comment by lesiki** [comment]
Good suggestion, yes I'll make time to add this.

**Comment by AsidStorm** [comment]
Hi @lesiki I made a pull request https://github.com/lesiki/google-meet-default-account/pull/3 for this feature.

**Comment by lesiki** [comment]
Merged #3 , I'll close this once the new release is approved in the chrome webstore.

**Comment by lesiki** [comment]
Went live in 1.1

**Comment by ssbarnea** [comment]
Not sure how this is supposed to work because even with force option I was never able to convince meet to start with the 2nd profile, always starting with the main profile.
