### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by mjaggard** [lesiki/google-meet-default-account#2]
I installed the extension from Chrome Web Store and set my authuser to 1 in the options but when I type `meet.google.com` into my browser I still get no authuser in the URL and my account is my default one.

**Comment by lesiki** [comment]
The main use case I had in mind was setting a default account when I open a specific Google Meet call link (e.g. when I've been added to meetings in my calendar), but maybe we could also extend it to work for the Google Meet homepage.

@mjaggard it should kick in when you open a specific meeting URL, e.g. `meet.google.com/exa-mpl-eee`, does that work?

**Comment by AsidStorm** [comment]
Hi @lesiki I made a pull request https://github.com/lesiki/google-meet-default-account/pull/3 that allows to redirect main page (and some more) too.

**Comment by lesiki** [comment]
Merged #3 , I'll close this once the new release is approved in the chrome webstore.

**Comment by lesiki** [comment]
This went live in 1.1
